ignore:
  - "src/main/resources/com/contentful/java/cma/build/GeneratedBuildParameters.java"  # ignore build resource folders
  - "*Test*"  # ignore all end to tests
  - "*E2E*"  # ignore all end to end tests

coverage:
  precision: 1
